### PR TITLE
Fixing 1.0.2

### PR DESCRIPTION
**Pull request by gpedro**
Removing unused folder, Fixing composer.json autoload and add some keywords.

### CODE REVIEW

**Comment by gpedro** [comment]
@artdarek ping

**Comment by gpedro** [comment]
@artdarek, please, release 1.0.2 again.

**Comment by artdarek** [comment]
@gpedro 1.0.3 released

**Comment by gpedro** [comment]
@artdarek I think it would be better to release 1.0.2 again, because the current version (1.0.2) it's not working.

**Pull request merged**
